"""data spine pgvector schema

Revision ID: 0001_data_spine_pgvector
Revises:
Create Date: 2026-05-21
"""

from alembic import op


revision = "0001_data_spine_pgvector"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE EXTENSION IF NOT EXISTS vector;

        CREATE TABLE IF NOT EXISTS users (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          mal_user_id BIGINT,
          username TEXT NOT NULL UNIQUE,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        CREATE TABLE IF NOT EXISTS ingestion_runs (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          source TEXT NOT NULL,
          job_type TEXT NOT NULL,
          status TEXT NOT NULL,
          cursor TEXT,
          items_seen INTEGER NOT NULL DEFAULT 0,
          items_written INTEGER NOT NULL DEFAULT 0,
          error TEXT,
          started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          finished_at TIMESTAMPTZ
        );

        CREATE TABLE IF NOT EXISTS source_records (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          source TEXT NOT NULL,
          content_type TEXT NOT NULL,
          source_item_id TEXT NOT NULL,
          payload_hash TEXT NOT NULL,
          payload_json JSONB NOT NULL,
          fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          source_updated_at TIMESTAMPTZ,
          UNIQUE (source, content_type, source_item_id, payload_hash)
        );

        CREATE TABLE IF NOT EXISTS canonical_items (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          content_type TEXT NOT NULL,
          title TEXT NOT NULL,
          synopsis TEXT,
          media_type TEXT,
          status TEXT,
          mean DOUBLE PRECISION,
          rank INTEGER,
          popularity INTEGER,
          nsfw TEXT,
          num_units INTEGER,
          payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        CREATE TABLE IF NOT EXISTS item_source_links (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          canonical_item_id BIGINT NOT NULL REFERENCES canonical_items(id),
          source TEXT NOT NULL,
          content_type TEXT NOT NULL,
          source_item_id TEXT NOT NULL,
          source_record_id BIGINT REFERENCES source_records(id),
          url TEXT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          UNIQUE (source, content_type, source_item_id)
        );

        CREATE TABLE IF NOT EXISTS item_field_sources (
          canonical_item_id BIGINT NOT NULL REFERENCES canonical_items(id),
          field_name TEXT NOT NULL,
          source TEXT NOT NULL,
          source_record_id BIGINT REFERENCES source_records(id),
          confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          PRIMARY KEY (canonical_item_id, field_name)
        );

        CREATE TABLE IF NOT EXISTS user_item_events (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id BIGINT NOT NULL REFERENCES users(id),
          canonical_item_id BIGINT NOT NULL REFERENCES canonical_items(id),
          content_type TEXT NOT NULL,
          event_type TEXT NOT NULL,
          source TEXT NOT NULL,
          source_event_id TEXT,
          status TEXT,
          score INTEGER,
          progress INTEGER,
          payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
          occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        CREATE INDEX IF NOT EXISTS idx_user_item_events_user ON user_item_events (user_id, canonical_item_id);
        CREATE INDEX IF NOT EXISTS idx_user_item_events_type ON user_item_events (event_type, source);

        CREATE TABLE IF NOT EXISTS item_traits (
          canonical_item_id BIGINT REFERENCES canonical_items(id),
          content_type TEXT,
          mal_id BIGINT,
          prompt_version TEXT NOT NULL,
          model_name TEXT NOT NULL,
          source_hash TEXT NOT NULL,
          traits_json JSONB NOT NULL,
          confidence DOUBLE PRECISION NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        CREATE UNIQUE INDEX IF NOT EXISTS idx_item_traits_canonical_unique
          ON item_traits (canonical_item_id, prompt_version)
        ;

        CREATE UNIQUE INDEX IF NOT EXISTS idx_item_traits_mal
          ON item_traits (content_type, mal_id, prompt_version)
          WHERE content_type IS NOT NULL AND mal_id IS NOT NULL;

        CREATE TABLE IF NOT EXISTS item_vectors (
          canonical_item_id BIGINT NOT NULL REFERENCES canonical_items(id),
          model_name TEXT NOT NULL,
          input_hash TEXT NOT NULL,
          embedding vector(1024) NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          PRIMARY KEY (canonical_item_id, model_name)
        );

        CREATE INDEX IF NOT EXISTS idx_item_vectors_embedding
          ON item_vectors USING hnsw (embedding vector_cosine_ops);

        CREATE TABLE IF NOT EXISTS recommendation_runs (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id BIGINT NOT NULL REFERENCES users(id),
          mode TEXT NOT NULL,
          mood TEXT,
          context_json JSONB NOT NULL,
          results_json JSONB NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        CREATE TABLE IF NOT EXISTS feedback_events (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          run_id BIGINT REFERENCES recommendation_runs(id),
          user_id BIGINT NOT NULL REFERENCES users(id),
          canonical_item_id BIGINT REFERENCES canonical_items(id),
          content_type TEXT NOT NULL,
          source TEXT NOT NULL DEFAULT 'manual',
          source_item_id TEXT,
          event_type TEXT NOT NULL,
          payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP TABLE IF EXISTS feedback_events;
        DROP TABLE IF EXISTS recommendation_runs;
        DROP TABLE IF EXISTS item_vectors;
        DROP TABLE IF EXISTS item_traits;
        DROP TABLE IF EXISTS user_item_events;
        DROP TABLE IF EXISTS item_field_sources;
        DROP TABLE IF EXISTS item_source_links;
        DROP TABLE IF EXISTS canonical_items;
        DROP TABLE IF EXISTS source_records;
        DROP TABLE IF EXISTS ingestion_runs;
        DROP TABLE IF EXISTS users;
        """
    )
