"""work graph

Revision ID: 0003_work_graph
Revises: 0002_item_traits_upsert_index
Create Date: 2026-05-21
"""

from alembic import op


revision = "0003_work_graph"
down_revision = "0002_item_traits_upsert_index"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS canonical_works (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          content_type TEXT NOT NULL,
          title TEXT NOT NULL,
          payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        CREATE TABLE IF NOT EXISTS item_relations (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          from_item_id BIGINT NOT NULL REFERENCES canonical_items(id),
          to_item_id BIGINT NOT NULL REFERENCES canonical_items(id),
          relation_type TEXT NOT NULL,
          source TEXT NOT NULL,
          confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0,
          evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          UNIQUE (from_item_id, to_item_id, relation_type, source)
        );

        CREATE TABLE IF NOT EXISTS item_work_links (
          canonical_item_id BIGINT PRIMARY KEY REFERENCES canonical_items(id),
          canonical_work_id BIGINT NOT NULL REFERENCES canonical_works(id),
          role TEXT NOT NULL,
          sequence_index INTEGER NOT NULL DEFAULT 0,
          is_entrypoint BOOLEAN NOT NULL DEFAULT false,
          confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0,
          source TEXT NOT NULL,
          evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        CREATE INDEX IF NOT EXISTS idx_item_work_links_work
          ON item_work_links (canonical_work_id, sequence_index);

        CREATE TABLE IF NOT EXISTS work_vectors (
          canonical_work_id BIGINT NOT NULL REFERENCES canonical_works(id),
          model_name TEXT NOT NULL,
          input_hash TEXT NOT NULL,
          embedding vector(1024) NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          PRIMARY KEY (canonical_work_id, model_name)
        );

        CREATE INDEX IF NOT EXISTS idx_work_vectors_embedding
          ON work_vectors USING hnsw (embedding vector_cosine_ops);
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP TABLE IF EXISTS work_vectors;
        DROP TABLE IF EXISTS item_work_links;
        DROP TABLE IF EXISTS item_relations;
        DROP TABLE IF EXISTS canonical_works;
        """
    )
